const quotes = [
    {"quote": "Where your treasure is, there will your heart be also.", "author": "Albus Dumbledore"},
    {"quote": "Not my daughter, you bitch!", "author": "Molly Weasley"},
    {"quote": "You think the dead we loved ever truly leave us? You think that we don’t recall them more clearly than ever in times of great trouble? Your father is alive in you, Harry, and shows himself plainly when you have need of him.", "author": "Albus Dumbledore"},
    {"quote": "Happiness can be found, even in the darkest of times, if one only remembers to turn on the light.", "author": "Albus Dumbledore"},
    {"quote": "Indeed, your failure to understand that there are things much worse than death has always been your greatest weakness.", "author":"Albus Dumbledore"},
    {"quote": "I say there are spots that don’t come off… Spots that never come off, d’you know what I mean.", "author": "Mad-Eye Moody"},
    {"quote": "Nothing like a nighttime stroll to give you ideas.", "author": "Mad-Eye Moody"},
    {"quote": "If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals.", "author": "Sirius Black"},
    {"quote": "I sometimes find, and I am sure you know the feeling, that I simply have too many thoughts and memories crammed into my mind…. At these times… I use the Pensieve. One simply siphons the excess thoughts from one’s mind, pours them into the basin, and examines them at one’s leisure.", "author": "Albus Dumbledore"},
    {"quote": "Curiosity is not a sin… But we should exercise caution with our curiosity… yes, indeed.", "author": "Albus Dumbledore"},
    {"quote": "In dreams, we enter a world that’s entirely our own.", "author": "Albus Dumbledore"},
    {"quote": "To the well-organized mind, death is but the next great adventure.", "author": "Albus Dumbledore"},
    {"quote": "We must try not to sink beneath our anguish, Harry, but battle on.", "author": "Albus Dumbledore"},
    {"quote": "It is the unknown we fear when we look upon death and darkness, nothing more.", "author": "Albus Dumbledore"},
    {"quote": "Ah, music. A magic beyond all we do here!", "author": "Albus Dumbledore"},
    {"quote": "Indifference and neglect often do much more damage than outright dislike …We wizards have mistreated and abused our fellows for too long, and we are now reaping our reward.", "author": "Albus Dumbledore"},
    {"quote": "People find it far easier to forgive others for being wrong than being right.", "author": "Albus Dumbledore"},
    {"quote": "It does not do to dwell on dreams and forget to live.", "author": "Albus Dumbledore"},
    {"quote": "Age is foolish and forgetful when it underestimates youth.", "author": "Albus Dumbledore"},
    {"quote": "When you have seen as much of life as I have, you will not underestimate the power of obsessive love.", "author": "Albus Dumbledore"},
    {"quote": "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", "author": "Albus Dumbledore"},
    {"quote": "Fear of a name increases fear of the thing itself.", "author": "Albus Dumbledore"},
    {"quote": "You sort of start thinking anything’s possible if you’ve got enough nerve.", "author": "Ginny Weasley"},
    {"quote": "Hearing voices no one else can hear isn’t a good sign, even in the wizarding world.", "author": "Ron Weasley"},
    {"quote": "It is our choices… that show what we truly are, far more than our abilities.", "author": "Albus Dumbledore"},
    {"quote": "Never trust anything that can think for itself if you can’t see where it keeps its brain.", "author": "Arthur Weasley"},
    {"quote": "As much money and life as you could want! The two things most human beings would choose above all – the trouble is, humans do have a knack of choosing precisely those things that are worst for them.", "author": "Albus Dumbledore"},
    {"quote": "There is no good or evil: only power and those too weak to seek it.", "author": "Quirinus Quirrell"},
    {"quote": "The mind is not a book, to be opened at will and examined at leisure. Thoughts are not etched on the inside of skulls, to be perused by an invader. The mind is a complex and many-layered thing.", "author": "Severus Snape"},
    {"quote": "Indifference and neglect often do much more damage than outright dislike.", "author": "Albus Dumbledore"},
    {"quote": "The truth is a beautiful and terrible thing, and should therefore be treated with caution.", "author": "Albus Dumbledore"},
    {"quote": "Youth cannot know how age thinks and feels. But old men are guilty if they forget what it was to be young.", "author": "Albus Dumbledore"},
    {"quote": "He chose the boy he thought most likely to be a danger to him … and notice this, Harry. He chose, not the pureblood (which according to his creed, is the only kind of wizard worth being or knowing), but the half-blood, like himself. He saw himself in you before he had ever seen you, and in marking you with that scar, he did not kill you, as he intended, but gave you powers, and a future, which have fitted you to escape him not once, but four times so far.", "author": "Albus Dumbledore"},
    {"quote": "Numbing the pain for a while will make it worse when you finally feel it.", "author": "Albus Dumbledore"},
    {"quote": "Time is making fools of us again.", "author": "Albus Dumbledore"}
  
];

  export default quotes;